#!/usr/bin/env python3
from pathlib import Path

path = Path('tools/prepare_v2127.py')
text = path.read_text(encoding='utf-8')
old = '''for model in TARGET_MODELS:\n    old = f'if (model == "{model}") return "experimental"'\n    new = f'if (model == "{model}") return "community_validated"'\n    job = replace_once(job, old, new, f"{model} model status")\n'''
new = '''job = replace_once(\n    job,\n    'if (is_2960(model)) return "experimental"',\n    'if (model ~ /^WS-C2960X-24TS/) return "community_validated"\\n      if (is_2960(model)) return "experimental"',\n    "WS-C2960X-24TS-L model status",\n)\nfor old, new, label in (\n    ('if (model ~ /^WS-C3560CG-8PC/) return "experimental"', 'if (model ~ /^WS-C3560CG-8PC/) return "community_validated"', 'WS-C3560CG-8PC-S model status'),\n    ('if (model == "SG500X-24") return "experimental"', 'if (model == "SG500X-24") return "community_validated"', 'SG500X-24 model status'),\n    ('if (model == "S5735-L8P4X-A1") return "experimental"', 'if (model == "S5735-L8P4X-A1") return "community_validated"', 'S5735-L8P4X-A1 model status'),\n    ('if (model == "S5720-12TP-LI-AC") return "experimental"', 'if (model == "S5720-12TP-LI-AC") return "community_validated"', 'S5720-12TP-LI-AC model status'),\n):\n    job = replace_once(job, old, new, label)\n\nfor old, new, label in (\n    ('else if (model ~ /^WS-C3560CG/) print "- INFO: Catalyst 3560-CG Experimental mapping loaded; contributor validation remains pending"', 'else if (model ~ /^WS-C3560CG/) print "- INFO: Catalyst 3560-CG Community Validated mapping loaded; Gi0/9 and Gi0/10 retain dual-purpose combo semantics"', '3560 report status'),\n    ('else if (model == "SG500X-24") print "- INFO: Cisco SG500X-24 Experimental mapping loaded from contribution evidence"', 'else if (model == "SG500X-24") print "- INFO: Cisco SG500X-24 Community Validated mapping loaded from real-hardware contribution evidence"', 'SG500X report status'),\n    ('else if (model == "S5735-L8P4X-A1") print "- INFO: Huawei S5735-L8P4X-A1 Experimental mapping loaded from repeated contribution evidence"', 'else if (model == "S5735-L8P4X-A1") print "- INFO: Huawei S5735-L8P4X-A1 Community Validated mapping loaded from repeated real-hardware evidence"', 'S5735 report status'),\n    ('else if (model == "S5720-12TP-LI-AC") print "- INFO: Huawei S5720-12TP-LI-AC Experimental mapping loaded with ifDescr fallback"', 'else if (model == "S5720-12TP-LI-AC") print "- INFO: Huawei S5720-12TP-LI-AC Community Validated physical mapping loaded with 1G SFP speed safeguards"', 'S5720 report status'),\n):\n    job = replace_once(job, old, new, label)\n'''
if text.count(old) != 1:
    raise SystemExit(f'ERROR: expected one old status block, found {text.count(old)}')
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8', newline='\n')
print('Corrected Discovery 2.1.27 preparation guards')
